"""One-off test: build and send the report right now.
Pass --weekly to force a weekly report, otherwise sends a daily report.
"""
import os, sys
sys.path.insert(0, ".")

from dotenv import load_dotenv
load_dotenv("../.env")

from email_report import (
    _fetch_candles_for_report, _run_all_backtests,
    build_daily_excel, build_weekly_excel, _send_email,
)
from config import now_ist

force_weekly = "--weekly" in sys.argv

now       = now_ist()
today_str = now.strftime("%Y-%m-%d")
is_friday = force_weekly or (now.weekday() == 4)

print("Fetching NIFTY candles...")
candles = _fetch_candles_for_report()
print(f"  Got {len(candles)} candles")

print("Running backtests...")
all_trades = _run_all_backtests(candles)
print(f"  Total completed trades: {len(all_trades)}")

if is_friday:
    week_label  = f"Week ending {now.strftime('%d %b %Y')}"
    print("Building WEEKLY Excel...")
    excel_bytes = build_weekly_excel(all_trades, week_label)
    filename    = f"backtest_weekly_{today_str}.xlsx"
    total_pnl   = round(sum(t.get("pnl", 0) for t in all_trades), 2)
    report_type = "Weekly"
    period      = week_label
else:
    report_date  = now.strftime("%A, %d %b %Y")
    print("Building DAILY Excel...")
    excel_bytes, today_trades = build_daily_excel(all_trades, today_str, report_date)
    filename     = f"backtest_daily_{today_str}.xlsx"
    total_pnl    = round(sum(t.get("pnl", 0) for t in today_trades), 2)
    report_type  = "Daily"
    period       = report_date

print(f"  Excel size: {len(excel_bytes):,} bytes")

sign  = "+" if total_pnl >= 0 else ""
color = "#1e8449" if total_pnl >= 0 else "#c0392b"
extra = ("Each sheet covers one trading day." if is_friday
         else "Each sheet covers one strategy (today's trades only).")

body = f"""
<html><body style="font-family:Arial,sans-serif;color:#2c3e50;">
<h2 style="color:#1a5276;">{report_type} Backtest P&amp;L Report — NIFTY (TEST)</h2>
<p><strong>Period:</strong> {period}</p>
<p><strong>Overall P&amp;L:</strong>
   <span style="color:{color};font-size:18px;font-weight:bold;">{sign}{total_pnl:.2f}</span>
</p>
<p>Excel attached. {extra}</p>
<hr/>
<p style="font-size:11px;color:#7f8c8d;">TEST SEND — Auto-generated by AlgoTrading platform.</p>
</body></html>
"""

print("Sending email...")
_send_email(
    subject=f"[AlgoTrading TEST] {report_type} P&L — {today_str}  ({sign}{total_pnl:.2f})",
    body=body,
    attachment_bytes=excel_bytes,
    filename=filename,
)
print("Done!")
