name: Run Algo Trading Script

on:
  workflow_dispatch:  # allows manual trigger
  schedule:
    - cron: "0 3 * * 1-5"  # optional: run every weekday at 08:30 AM IST (03:00 UTC)

jobs:
  run-trading-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: |
          uv sync

      - name: Run AlgoTrade script
        env:
            DHAN_BOT_TOKEN: ${{ secrets.DHAN_BOT_TOKEN }}
            DHAN_CLIENT_CODE: ${{ secrets.DHAN_CLIENT_CODE }}
            DHAN_TOKEN_ID: ${{ secrets.DHAN_TOKEN_ID }}
            GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
            RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
            GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
            
        run: |
          uv run dhan_nifty_breakout.py
